# Generated by Django 4.2.2 on 2023-06-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationslot',
            name='total_slots',
        ),
    ]
