# Generated by Django 4.2.2 on 2023-06-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_vaccinationslot_total_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationslot',
            name='available_slots',
            field=models.IntegerField(default=10),
        ),
    ]
